apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  namespace: default
  labels:
    app: jks
spec:
  containers:
  - name: jenkinspod
    image: cansentay/jenkins
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: "storage"
      mountPath: "/logs"
  volumes:
    - name: "storage"
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jkssvc
  namespace: default
spec:
  selector:
    app: jks
  type: LoadBalancer
  ports:
  - name: jksport
    protocol: TCP
    port: 8080
